[emc]
front = "10.36.51.16"
port = 20003
user = "front"
pass = "12345678"

# 中金所
exchange = 102
# 单位: us
interval = 1
# 单位: min
valid = 5

priorities = [3, 2]

[[emc.seats]]
index = 4
address = "172.24.16.51"

[[emc.seats]]
index = 5
address = "172.24.16.54"

[[emc.seats]]
index = 6
address = "172.24.16.52"

[[emc.seats]]
index = 7
address = "172.24.16.53"

[[emc.seats]]
index = 8
address = "172.24.16.55"

[[emc.seats]]
index = 9
address = "172.24.16.57"

[[emc.seats]]
index = 10
address = "172.24.16.51"

[[emc.seats]]
index = 11
address = "172.24.16.51"