// Code generated by "stringer -type messageType -linecomment"; DO NOT EDIT.

package ctl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgUnknown-0]
	_ = x[MsgCommand-1]
	_ = x[MsgResult-2]
	_ = x[MsgBroadCast-3]
}

const _messageType_name = "UnknownCommandResultBroadCast"

var _messageType_index = [...]uint8{0, 7, 14, 20, 29}

func (i messageType) String() string {
	if i >= messageType(len(_messageType_index)-1) {
		return "messageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _messageType_name[_messageType_index[i]:_messageType_index[i+1]]
}
